;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-newline
        c-electric-semi&comma
        eval-print-last-sexp
        keyboard-escape-quit
        smex
        suspend-frame
        ))

(setq mc/cmds-to-run-once
      '(
        autopair-insert-or-skip-quote
        beginning-of-visual-line
        c-electric-delete-forward
        comment-region
        switch-window
        ))
